namespace OpenCymd.Nps.Plugin.Native
{
    /// <summary>
    /// The RADIUS_ATTRIBUTE_TYPE type enumerates the possible types for a RADIUS attribute.
    /// http://msdn.microsoft.com/en-us/library/windows/desktop/bb892011(v=vs.85).aspx
    /// </summary>
    public enum RADIUS_ATTRIBUTE_TYPE : uint
    {
        ratMinimum                  = 0,
        ratUserName                 = 1,
        ratUserPassword             = 2,
        ratCHAPPassword             = 3,
        ratNASIPAddress             = 4,
        ratNASPort                  = 5,
        ratServiceType              = 6,
        ratFramedProtocol           = 7,
        ratFramedIPAddress          = 8,
        ratFramedIPNetmask          = 9,
        ratFramedRouting            = 10,
        ratFilterId                 = 11,
        ratFramedMTU                = 12,
        ratFramedCompression        = 13,
        ratLoginIPHost              = 14,
        ratLoginService             = 15,
        ratLoginPort                = 16,
        ratReplyMessage             = 18,
        ratCallbackNumber           = 19,
        ratCallbackId               = 20,
        ratFramedRoute              = 22,
        ratFramedIPXNetwork         = 23,
        ratState                    = 24,
        ratClass                    = 25,
        ratVendorSpecific           = 26,
        ratSessionTimeout           = 27,
        ratIdleTimeout              = 28,
        ratTerminationAction        = 29,
        ratCalledStationId          = 30,
        ratCallingStationId         = 31,
        ratNASIdentifier            = 32,
        ratProxyState               = 33,
        ratLoginLATService          = 34,
        ratLoginLATNode             = 35,
        ratLoginLATGroup            = 36,
        ratFramedAppleTalkLink      = 37,
        ratFramedAppleTalkNetwork   = 38,
        ratFramedAppleTalkZone      = 39,
        ratAcctStatusType           = 40,
        ratAcctDelayTime            = 41,
        ratAcctInputOctets          = 42,
        ratAcctOutputOctets         = 43,
        ratAcctSessionId            = 44,
        ratAcctAuthentic            = 45,
        ratAcctSessionTime          = 46,
        ratAcctInputPackets         = 47,
        ratAcctOutputPackets        = 48,
        ratAcctTerminationCause     = 49,
        ratCHAPChallenge            = 60,
        ratNASPortType              = 61,
        ratPortLimit                = 62,
        ratTunnelType               = 64,
        ratMediumType               = 65,
        ratTunnelPassword           = 69,
        ratTunnelPrivateGroupID     = 81,
        ratNASIPv6Address           = 95,
        ratFramedInterfaceId        = 96,
        ratFramedIPv6Prefix         = 97,
        ratLoginIPv6Host            = 98,
        ratFramedIPv6Route          = 99,
        ratFramedIPv6Pool           = 100,
        ratCode                     = 262,
        ratIdentifier               = 263,
        ratAuthenticator            = 264,
        ratSrcIPAddress             = 265,
        ratSrcPort                  = 266,
        ratProvider                 = 267,
        ratStrippedUserName         = 268,
        ratFQUserName               = 269,
        ratPolicyName               = 270,
        ratUniqueId                 = 271,
        ratExtensionState           = 272,
        ratEAPTLV                   = 273,
        ratRejectReasonCode         = 274,
        ratCRPPolicyName            = 275,
        ratProviderName             = 276,
        ratClearTextPassword        = 277,
        ratSrcIPv6Address           = 278
    }
}