// <auto-generated/>: silence stylecop

// --------------------------------------------------------------------------------------------------------------------
// <copyright>
//   Copyright (C) 2012-2013 University of Applied Sciences Northwestern Switzerland
//   
//   This library is free software; you can redistribute it and/or
//   modify it under the terms of the GNU Lesser General Public
//   License as published by the Free Software Foundation; either
//   version 2.1 of the License, or (at your option) any later version.
//   
//   This library is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//   Lesser General Public License for more details.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

// ReSharper disable InconsistentNaming
namespace OpenCymd.Nps.Plugin.Native
{
    using System.Runtime.InteropServices;

    /// <summary>
    /// Struct representing the layout of a RADIUS Vendor-Specific attribute. This
    /// is useful when interpreting the RADIUS_ATTRIBUTE lpValue field when
    /// dwAttrType is ratVendorSpecific.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal class RADIUS_VSA_FORMAT
    {
        /// <summary>
        /// The SMI Network Management Private Enterprise Code of the vendor for this attribute.
        /// </summary>
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)]
        public byte[] VendorId;

        /// <summary>
        /// Numeric identifier for the attribute assigned by the vendor.
        /// </summary>
        public byte VendorType;

        /// <summary>
        /// The combined size of the VendorType, VendorLength, AttributeSpecific members.
        /// </summary>
        public byte VendorLength;

        // attribute data begins here: Array of bytes that contains information for this attribute.
        // BYTE AttributeSpecific[1];
    }
}
// ReSharper restore InconsistentNaming
