// <auto-generated/>: silence stylecop

// --------------------------------------------------------------------------------------------------------------------
// <copyright>
//   Copyright (C) 2012-2013 University of Applied Sciences Northwestern Switzerland
//   
//   This library is free software; you can redistribute it and/or
//   modify it under the terms of the GNU Lesser General Public
//   License as published by the Free Software Foundation; either
//   version 2.1 of the License, or (at your option) any later version.
//   
//   This library is distributed in the hope that it will be useful,
//   but WITHOUT ANY WARRANTY; without even the implied warranty of
//   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
//   Lesser General Public License for more details.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------

// ReSharper disable InconsistentNaming
namespace OpenCymd.Nps.Plugin.Native
{
    /// <summary>
    /// Enumerates the different actions an extension DLL can generate in response to an Access-Request.
    /// </summary>
    internal enum RADIUS_ACTION
    {
        /// <summary>
        /// NPS continues to process the request. NPS also continues to call RadiusExtensionProcess in other Extension DLLs.
        /// </summary>
        raContinue,

        /// <summary>
        /// Return an Access-Reject packet. The Access-Request is declined. In this case, NPS does not call RadiusExtensionProcess in any other Extension DLLs.
        /// </summary>
        raReject,

        /// <summary>
        /// NPS accepts the Access-Request. NPS does not continue to call RadiusExtensionProcess in this case. However, it does continue to obtain authorizations for the user requesting access.
        /// </summary>
        raAccept
    }
}
// ReSharper restore InconsistentNaming