// <auto-generated/>: silence stylecop
// ReSharper disable InconsistentNaming
namespace OpenCymd.Nps.Plugin.Native
{
    /// <summary>
    /// Enumerates the different actions an extension DLL can generate in response to an Access-Request.
    /// </summary>
    internal enum RADIUS_ACTION
    {
        /// <summary>
        /// NPS continues to process the request. NPS also continues to call RadiusExtensionProcess in other Extension DLLs.
        /// </summary>
        raContinue,

        /// <summary>
        /// Return an Access-Reject packet. The Access-Request is declined. In this case, NPS does not call RadiusExtensionProcess in any other Extension DLLs.
        /// </summary>
        raReject,

        /// <summary>
        /// NPS accepts the Access-Request. NPS does not continue to call RadiusExtensionProcess in this case. However, it does continue to obtain authorizations for the user requesting access.
        /// </summary>
        raAccept
    }
}
// ReSharper restore InconsistentNaming